# Generated by Django 6.0.3 on 2026-03-18 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_course_exam_examresult_lesson_question_resource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='exam',
            name='preparation_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='average_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='examresult',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='medical_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_contact',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='AdminMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('mandatory_for_all', models.BooleanField(default=False)),
                ('attendees', models.ManyToManyField(blank=True, related_name='admin_meetings', to='students.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='present', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marked_attendance', to='students.teacher')),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
    ]
