# Generated by Django 6.0.3 on 2026-03-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_expense_feetier_income_invoice_studentdiscount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='learning_goals',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='plan_status',
            field=models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('pending_renewal', 'Pending Renewal'), ('inactive', 'Inactive'), ('completed', 'Completed'), ('scheduled_leave', 'Scheduled Leave'), ('discontinued', 'Discontinued')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='plan_type',
            field=models.CharField(choices=[('one-on-one', 'One-on-One'), ('batch', 'Batch'), ('twin', 'Twin'), ('revision', 'Revision')], default='one-on-one', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='sessions_per_week',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='special_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='students', to='students.subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='syllabus',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
