# Generated by Django 6.0.3 on 2026-03-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_teacher_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmeeting',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
