# Generated by Django 6.0.3 on 2026-03-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_resource_course_alter_resource_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
