# Generated by Django 6.0.3 on 2026-03-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_resource_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
        migrations.AddField(
            model_name='resource',
            name='section',
            field=models.CharField(choices=[('syllabus', 'Syllabus'), ('notes', 'Class Notes'), ('assignment', 'Assignments'), ('reference', 'Reference Materials'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
