# Generated by Django 6.0.3 on 2026-03-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_resource_file_resource_section_alter_resource_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF Document'), ('video', 'Video Link'), ('video_file', 'Video Upload'), ('link', 'External Link'), ('audio', 'Audio Note')], max_length=10),
        ),
        migrations.AlterField(
            model_name='resource',
            name='section',
            field=models.CharField(choices=[('syllabus', 'Syllabus'), ('notes', 'Class Notes'), ('assignment', 'Assignments'), ('reference', 'Reference Materials'), ('video', 'Videos'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
