# Generated by Django 6.0.3 on 2026-03-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_resource_file_type_alter_resource_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_mode',
            field=models.CharField(choices=[('offline', 'Offline'), ('online', 'Online')], default='offline', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('short', 'Short Answer'), ('long', 'Long Answer')], max_length=10),
        ),
    ]
