# Generated by Django 6.0.3 on 2026-03-25 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_studentanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examresult',
            old_name='average_score',
            new_name='percentage',
        ),
        migrations.AddField(
            model_name='examresult',
            name='grade',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='examresult',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('published', 'Published')], default='draft', max_length=15),
        ),
        migrations.AddField(
            model_name='examresult',
            name='total_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='SubjectMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.FloatField()),
                ('max_marks', models.FloatField(default=100.0)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_performance', to='students.examresult')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject')),
            ],
        ),
    ]
