# Generated by Django 6.0.3 on 2026-03-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_rename_average_score_examresult_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachersalary',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='teachersalary',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='teachersalary',
            name='date',
        ),
        migrations.AddField(
            model_name='teachersalary',
            name='basic_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='teachersalary',
            name='extra_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='teachersalary',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachersalary',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='teachersalary',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=10),
        ),
    ]
