# Generated by Django 6.0.3 on 2026-03-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_add_teacher_monthly_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersalary',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='teachersalary',
            name='extra_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='teachersalary',
            name='month',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teachersalary',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
