# Generated by Django 6.0.3 on 2026-03-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_cleanup_teacher_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersalary',
            name='deductions_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='teachersalary',
            name='earnings_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='teachersalary',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='teachersalary',
            name='leave_days',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teachersalary',
            name='paid_days',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teachersalary',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('cheque', 'Cheque')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teachersalary',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='teachersalary',
            name='total_working_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='teachersalary',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='teachersalary',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('pending', 'Pending')], default='unpaid', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='teachersalary',
            unique_together={('teacher', 'month')},
        ),
    ]
