# Generated by Django 6.0.3 on 2026-03-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_creditadvance_remove_studentdiscount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='person_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
