# Generated by Django 6.0.3 on 2026-03-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_financialtransaction_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpayment',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial'), ('unpaid', 'Unpaid')], default='pending', max_length=10),
        ),
    ]
