# Generated by Django 6.0.3 on 2026-03-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_remove_examresult_grade_remove_examresult_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='grade',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='examresult',
            name='percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
