# Generated by Django 6.0.3 on 2026-04-01 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_examresult_grade_examresult_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='requires_submission',
            field=models.BooleanField(default=False, help_text='Whether students must submit/upload to complete this note'),
        ),
        migrations.AddField(
            model_name='resource',
            name='target_grade',
            field=models.CharField(blank=True, help_text='Target class/standard for this resource (e.g. Class 10)', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='NoteAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=15)),
                ('submission_file', models.FileField(blank=True, null=True, upload_to='note_submissions/')),
                ('submission_text', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='students.resource')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_assignments', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('note', 'student')},
            },
        ),
    ]
