# Generated by Django 6.0.3 on 2026-04-06 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_resource_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('evaluated', 'Evaluated'), ('published', 'Published'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='OnlineClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(default='GENERAL', max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('link', models.URLField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_classes', to='students.teacher')),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
