# Generated by Django 6.0.3 on 2026-04-06 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0027_alter_examresult_status_onlineclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_time', models.DateTimeField()),
                ('meeting_link', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('students', models.ManyToManyField(blank=True, related_name='teacher_meetings', to='students.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_meetings', to='students.teacher')),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
    ]
