# Generated by Django 6.0.3 on 2026-04-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0028_teachermeeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmeeting',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='adminmeeting',
            name='meeting_type',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=15),
        ),
    ]
