# Generated by Django 6.0.3 on 2026-04-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0029_adminmeeting_meeting_link_adminmeeting_meeting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmeeting',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
