# Generated by Django 6.0.3 on 2026-04-07 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0030_adminmeeting_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('q_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('descriptive', 'Descriptive')], default='mcq', max_length=20)),
                ('points', models.IntegerField(default=1)),
                ('option_a', models.CharField(blank=True, max_length=200)),
                ('option_b', models.CharField(blank=True, max_length=200)),
                ('option_c', models.CharField(blank=True, max_length=200)),
                ('option_d', models.CharField(blank=True, max_length=200)),
                ('correct_option', models.CharField(blank=True, help_text='A, B, C, or D', max_length=1)),
                ('explanation', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaperAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in-progress', 'In Progress'), ('submitted', 'Submitted'), ('evaluated', 'Evaluated')], default='in-progress', max_length=20)),
                ('score', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_attempts', to='students.student')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True)),
                ('selected_option', models.CharField(blank=True, max_length=1)),
                ('marks_obtained', models.FloatField(default=0.0)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='students.paperattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.paperquestion')),
            ],
        ),
        migrations.CreateModel(
            name='PreviousYearPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('exam_name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('total_marks', models.PositiveIntegerField(default=100)),
                ('instructions', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='previous_papers/')),
                ('mode', models.CharField(choices=[('practice', 'Practice Mode'), ('exam', 'Exam Mode')], default='practice', max_length=20)),
                ('is_premium', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_papers', to='students.course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_papers', to='students.subject')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.teacher')),
            ],
            options={
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='paperquestion',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='students.previousyearpaper'),
        ),
        migrations.CreateModel(
            name='PaperPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_signature', models.CharField(blank=True, max_length=200)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.previousyearpaper')),
            ],
        ),
        migrations.AddField(
            model_name='paperattempt',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='students.previousyearpaper'),
        ),
    ]
