# Generated by Django 6.0.3 on 2026-04-07 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0031_paperquestion_paperattempt_paperanswer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousyearpaper',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_papers', to='students.course'),
        ),
        migrations.AlterField(
            model_name='previousyearpaper',
            name='exam_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
