# Generated by Django 6.0.3 on 2026-04-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0032_alter_previousyearpaper_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='plan_status',
            field=models.CharField(choices=[('lead', 'Lead'), ('active', 'Active'), ('pending_renewal', 'Pending Renewal'), ('discontinued', 'Discontinued'), ('new', 'New'), ('inactive', 'Inactive'), ('completed', 'Completed'), ('scheduled_leave', 'Scheduled Leave')], default='new', max_length=20),
        ),
    ]
