# Generated by Django 6.0.3 on 2026-04-14 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0033_alter_student_plan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assigned_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to='students.teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='lead_source',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
