# Generated by Django 6.0.3 on 2026-04-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0034_student_assigned_teacher_student_lead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='reference_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
