# Generated by Django 6.0.3 on 2026-04-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0036_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_address',
            field=models.TextField(blank=True),
        ),
    ]
