# Generated by Django 6.0.3 on 2026-04-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0037_student_batch_student_permanent_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpayment',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial'), ('unpaid', 'Unpaid'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
