# Generated by Django 6.0.3 on 2026-04-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0038_alter_studentpayment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
