# Generated by Django 6.0.3 on 2026-04-17 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0040_holiday_teacherattendance_check_in_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Campus', max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, default=28.6139, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=77.209, max_digits=9)),
                ('radius_meters', models.IntegerField(default=50)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'School Settings',
            },
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='attendance_source',
            field=models.CharField(choices=[('admin', 'Admin Marked'), ('self', 'Teacher Self Check-in')], default='admin', max_length=10),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='check_in_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='check_in_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='check_in_selfie',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_selfies/in/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='check_in_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='check_out_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='check_out_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='check_out_selfie',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_selfies/out/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='check_out_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='corrected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_attendance_corrected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='correction_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='correction_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='distance_meters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='is_corrected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('leave', 'Leave'), ('half_day', 'Half Day'), ('holiday', 'Holiday'), ('checked_in', 'Checked-in'), ('checked_out', 'Checked-out'), ('not_marked', 'Not Marked'), ('regularization_pending', 'Regularization Pending'), ('corrected', 'Corrected')], default='present', max_length=25),
        ),
        migrations.CreateModel(
            name='RegularizationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('request_type', models.CharField(choices=[('missed_check_in', 'Missed Check-in'), ('missed_check_out', 'Missed Check-out'), ('wrong_time', 'Wrong Time Marked'), ('location_issue', 'Location Issue'), ('selfie_issue', 'Selfie Issue'), ('other', 'Other')], max_length=20)),
                ('reason', models.TextField()),
                ('requested_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regularization_requests', to='students.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
