# Generated by Django 6.0.3 on 2026-04-17 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0041_schoolsettings_teacherattendance_attendance_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularizationrequest',
            name='requested_time',
        ),
        migrations.AddField(
            model_name='regularizationrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regularizationrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_regularizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regularizationrequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attendance_regularization/'),
        ),
        migrations.AddField(
            model_name='regularizationrequest',
            name='original_check_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regularizationrequest',
            name='original_check_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regularizationrequest',
            name='original_status',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='regularizationrequest',
            name='requested_check_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regularizationrequest',
            name='requested_check_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regularizationrequest',
            name='request_type',
            field=models.CharField(choices=[('missed_check_in', 'Missed Check-in'), ('missed_check_out', 'Missed Check-out'), ('wrong_check_in_time', 'Wrong Check-in Time'), ('wrong_check_out_time', 'Wrong Check-out Time'), ('full_day_correction', 'Full Day Correction'), ('other', 'Other')], max_length=25),
        ),
    ]
