# Generated by Django 6.0.3 on 2026-04-20 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0042_remove_regularizationrequest_requested_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='location_source',
            field=models.CharField(choices=[('search', 'Search'), ('map', 'Map Selection'), ('current', 'Current Location')], default='map', max_length=20),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geofence_updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
