# Generated by Django 6.0.3 on 2026-04-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0043_schoolsettings_location_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='assigned_classes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='teacher',
            name='current_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='permanent_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_photos/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
