# Generated by Django 6.0.3 on 2026-04-22 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0045_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='needs_password_change',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=15)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_requests', to='students.teacher')),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
    ]
