# Generated by Django 6.0.3 on 2026-04-23 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0048_leaverequest_attachment_leavetype_is_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherLeaveAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_days', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='students.leavetype')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_allocations', to='students.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'leave_type')},
            },
        ),
    ]
