# Generated by Django 6.0.3 on 2026-03-09 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_examschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='examschedule',
            name='auto_submit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='buffer_time',
            field=models.IntegerField(default=0, help_text='Buffer time in minutes'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='duration',
            field=models.IntegerField(default=60, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='mixed_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='timer_expiry_action',
            field=models.CharField(choices=[('AUTO_SUBMIT', 'Auto-submit'), ('ALLOW_OVERTIME', 'Allow Overtime')], default='AUTO_SUBMIT', max_length=20),
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('SHORT', 'Short Test'), ('LONG', 'Long Test'), ('YES_NO', 'Yes/No')], max_length=10)),
                ('text', models.TextField()),
                ('marks', models.IntegerField(default=1)),
                ('order', models.IntegerField(default=0)),
                ('payload', models.JSONField(default=dict, help_text='Stores options, correct answers, etc.')),
                ('media', models.FileField(blank=True, null=True, upload_to='exam_media/')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.examschedule')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
