# Generated by Django 6.0.3 on 2026-03-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_examschedule_auto_submit_examschedule_buffer_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Drop', 'Drop'), ('Graduate', 'Graduate')], default='Active', max_length=20),
        ),
    ]
