# Generated by Django 6.0.3 on 2026-03-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admission Manager', 'Admission Manager'), ('Education Manager', 'Education Manager'), ('Tutor', 'Tutor'), ('Account Manager', 'Account Manager'), ('Admin', 'Admin'), ('Student', 'Student')], max_length=50),
        ),
    ]
