# Generated by Django 6.0.3 on 2026-03-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Graduate', 'Graduate')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Scheduled Leave', 'Scheduled Leave'), ('Leave', 'Leave'), ('Resigned', 'Resigned')], default='Active', max_length=50),
        ),
    ]
