# Generated by Django 6.0.3 on 2026-03-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_student_status_alter_tutor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='examschedule',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
