# Generated by Django 6.0.3 on 2026-03-12 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_venue_examschedule_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examschedule',
            name='venue',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
