# Generated by Django 6.0.3 on 2026-03-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_examschedule_venue_delete_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
