# Generated by Django 6.0.3 on 2026-03-12 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_income_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.plan'),
        ),
    ]
